#!/usr/bin/env bash
# Script that displays the content of the file /etc/passwd, using the while loop + IFS
while IFS=":" read -r USERNAME PASSWORD USERID GROUP_ID USERIDinfo HOMEDIR CMD
do
  echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOMEDIR and rides $CMD. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $USERIDinfo"
done < /etc/passwd
