#!/usr/bin/env bash
# prints numbers considered supersitious in certain cultures
i=1

while ((i <= 20))
do
    echo $i
    case $i in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad lack from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((i++))
done
